package os.nut.drools.recharge;

import com.rkylin.risk.service.bean.RechargeFactor;

import com.rkylin.risk.service.bean.RechargeCode;

rule "rechargetime1"
    no-loop true
    salience 84
    when
         recharge : RechargeFactor(rechargetime >= 3&&rechargetime<5)
         code:RechargeCode()
    then
        code.setRechargetime("recRechargetime01");

end

rule "rechargetime2"
    no-loop true
    salience 83
    when
         recharge : RechargeFactor(rechargetime >= 1&&rechargetime<3 )
         code:RechargeCode()
    then
        code.setRechargetime("recRechargetime02");
end

rule "rechargetime3"
    no-loop true
    salience 82
    when
         recharge : RechargeFactor((rechargetime >= 23&&rechargetime<24)||(rechargetime>=0&&rechargetime<1))
         code:RechargeCode()
    then
        code.setRechargetime("recRechargetime03");
end

rule "rechargetime4"
    no-loop true
    salience 81
    when
         recharge : RechargeFactor(rechargetime >= 5&&rechargetime<7)
         code:RechargeCode()
    then
        code.setRechargetime("recRechargetime04");
end

rule "rechargetime5"
    no-loop true
    salience 80
    when
         recharge : RechargeFactor(rechargetime >= 7&&rechargetime<23)
         code:RechargeCode()
    then
        code.setRechargetime("recRechargetime05");
end